wandb_version: 1

speed:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    code_path: code/loading_main.py
    python_version: 3.8.0
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703174826.586029
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.0
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
